import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";

import { AppProvider } from "./providers";




import DATAheader from '../vlastnekomponenty/header/DATAheader'
const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default   function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {




  return (
    <html
      lang="en"
      className={`${figtree.variable}  h-full antialiased`}
    >
         
      <body className="min-h-full flex flex-col font-[var(--font-figtree)]">
         <AppProvider>
          <DATAheader></DATAheader>
      
        {children}
           </AppProvider>
        </body>

      
    </html>
  );
}
