import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import ScrollToTop from '../vlastnekomponenty/scrolovanie'
import { AppProvider } from "./providers";
import FOOTETIK from '../vlastnekomponenty/footer/footerzobrazovanie'


import DATAheader from '../vlastnekomponenty/header/DATAheader'
const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};





export default   function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {





  return (
    <html
      lang="en"
      className={`${figtree.variable}  h-full antialiased`}
    >

      <body className="min-h-full flex flex-col font-[var(--font-figtree)]">
         <ScrollToTop></ScrollToTop>
         <AppProvider>
          <DATAheader></DATAheader>
      
        {children}
        <FOOTETIK
        ></FOOTETIK>
        {/* <div className="w-full h-[900px] bg-amber-500"></div> */}
           </AppProvider>

           
        
        </body>

      
    </html>
  );
}
